---
title: "Pulling data from Comcare to R"
author: "Chris LeBoa"
date: "`r Sys.Date()`"
output: 
  word_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r message=FALSE, warning=FALSE}
# Libraries
#install.packages("haven")
library(tidyverse)
library(haven)
library(fs)
library(tableone)
```

```{r message=FALSE, warning=FALSE}
# Load Data


## CCS Data 
ccs_data_ch_cdc <- read_sas("/Users/ChrisLeBoa/Box Sync/CDC_Typhoid_data/ccs_ch_2020_03_18.sas7bdat")
  ##This is the Child based file with the addition of specific CDC variables 
ccs_data_ch <- read_sas("/Users/ChrisLeBoa/Box Sync/CDC_Typhoid_data/ccs_ch__2020_04_24.sas7bdat")
 ## Child data missing the CDC variables 
ccs_data_hh <- read_sas("/Users/ChrisLeBoa/Box Sync/CDC_Typhoid_data/ccs_hh__2020_04_24.sas7bdat")
  ## Household level data from the CDC 

## Hospital Level Data 
hospital_data <- read_sas("/Users/ChrisLeBoa/Box Sync/CDC_Typhoid_data/tcv_all__2020_07_06.sas7bdat")
  ## Hospital Lavel 

## Not sure 
bcr_data <- read_sas("/Users/ChrisLeBoa/Box Sync/CDC_Typhoid_data/bcr__2020_04_02.sas7bdat")

# Write out data 


```


```{r message=FALSE, warning=FALSE}


# Parameters 

sex_recode <- 
  c(
  `1` = "Male",
  `2` = "Female"
)

yes_no_recode <- 
   c(
  `1` = "Yes",
  `0` = "No"
)

hhead_recode <- c(
  `1` = "Respondent",
`2` = "Father of child", 
`3` = "Mother of child", 
`4` = "Grandparent of child", 
`88` = "Other",
`99` = "Declined to answer"
)

status_recode <- c(
  INT = "Interviewed-Eligible",
  ZEH = "Discovered no/zero eligible HH members",
  REF = "Refused-Eligible",
  VAC = "Clearly vacant house",
  UNA =  "Unavailable-believed to be eligible",
  NAU = "Not available-eligbility unconfirmed",
  NNC = "Not Available- Non-eligibility confirmed"
)

hh_edu_recode <- c(
  `1` = "Illiterate",
  `2` = "Primary school certificate (through Grade 4)",
  `3` = "Middle school certificate (Grade 5 - 10)",
  `4` = "High school certificate (Grade 11 - 12)",
  `5` = "Intermediate or post high school diploma",
  `6` = "Graduate (Bachelors degree)",
  `7` = "Post graduate, profession, or honors"
)

hh_occu_recode <- c(
  `1` = "Legislators, Senior Officials & Managers",
 `2` = "Professionals (e.g. Doctors, Engineers, Bank managers)",
 `3` = "Technicians and Associate Professionals", 
 `4` = "Clerks",
 `5` = "Skilled Workers and Shop & Market Sales Workers",
 `6` = "Skilled Agricultural & Fishery Workers",
 `7` = "Craft & Related Trade Workers",
 `8` = "Plant & Machine Operators and Assemblers",
 `9` = "Elementary Occupation (e.g. Domestic servant, peon, watchman)",
 `10` = "Mathadi or quarry workers",
 `11` = "Unemployed",
 `88` = "Other",
 `99` = "Refused"
)

toilet_recode <- c(
  `1` = "No facility / open defecation",
  `2` = "Traditional pit latrine",
  `3` = "Sarvajanik toilet (public toilets on the streets)",
  `4` = "Flush toilet",
  `88` = "Other", 
  `99` = "Refused"
)

child_schooling_recode <- c(
  `1` = "Yes", 
  `2` = "Not of school age",
  `3` = "Never attended school", 
  `99` = "DK/Refused"
)

child_schooling_level_recode <- c(
  `1` = "Illiterate",
  `2` = "Primary school certificate (through Grade 4)",
  `3` = "Middle school certificate (Grade 5 - 10)",
  `4` = "High school certificate (Grade 11 - 12)",
  `99` ="Declined to answer"
)

yes_no_school_recode <- 
   c(
  `1` = "Yes",
  `0` = "No", 
  `2` = "Child doesn’t attend school"
)



```

# CCS Enrollment Numbers 
```{r}
# ccs_data_ch_cdc %>% 
#   count(hosp, PHASE)
# 
# glimpse(ccs_data_hh)


#view(ccs_data_ch_cdc) 


#Breakdown of Status of households approached 
ccs_data_hh %>% 
  group_by(PHASE) %>% 
  count(status) %>% 
  arrange(desc(n)) %>% 
  pivot_wider(names_from = PHASE, names_prefix = "Phase ", values_from = n) %>% 
 transmute("Enrollment status" = recode(status, !!!status_recode), `Phase 1`, `Phase 2`) %>% 
  knitr::kable()


#Children enrolled 
ccs_data_ch %>% 
  group_by(PHASE) %>% 
  count(status) %>% 
  arrange(desc(n)) %>% 
  pivot_wider(names_from = PHASE, names_prefix = "Phase ", values_from = n) %>% 
 transmute("Children Enrollment" = recode(status, !!!status_recode), `Phase 1`, `Phase 2`) %>% 
   knitr::kable()

ccs_data_ch_cdc %>% 
  count(fever_sch30)

```

#Household Characteristics 

```{r, include=FALSE}

ccs_data_hh_formatted <- 
  ccs_data_hh %>% 
  filter(status == "INT") %>% 
  transmute(
    "Age Respondent" = ve_agerel, 
    "PHASE" = PHASE,
    "Number of Children" = children,
    "Sex Respondent" = recode(ve_sexresp, !!!sex_recode), 
    "Household Head (HH)" = recode(ve_hhead, !!!hhead_recode), 
    "HH Education"= recode(ve_hheadedu, !!!hh_edu_recode), 
    "HH Occupation" = recode(ses_hhhocu, !!!hh_occu_recode), 
    "Spending (Rupees)" = ses_spend,
    "Drinking Water Source" = 
      case_when(
        ses_watsrc == 1 |ses_watsrc == 2 ~ "Piped Water", 
        ses_watsrc == 3  ~ "Public Tap", 
        ses_watsrc == 6 |ses_watsrc == 8 ~ "Unprotected Well/Spring", 
        ses_watsrc == 7  ~ "Protected Well", 
        ses_watsrc == 10  ~ "Tanker Truck", 
        ses_watsrc == 13 ~ "Bottled water", 
        TRUE ~ NA_character_
      ), 
    "Water Treatment" = recode(ses_watsafe, !!!yes_no_recode), 
    "Hand Wash Location" = recode(ses_hwplace, !!!yes_no_recode), 
    "Hand Wash Water" = recode(ses_hwwater, !!!yes_no_recode),
    "Hand Wash Soap" = recode(ses_hwsoap_a, !!!yes_no_recode),
    "Toilet Type" = recode(ses_toitype, !!!toilet_recode), 
    "Shared Toilet" = recode(ses_toiletshare, !!!yes_no_recode)
  )

ccs_dara_ch_formatted <- 
  ccs_data_ch_cdc %>% 
  transmute(
    "Houshold Size" = numhh, 
    "PHASE" = PHASE,
    "Chuld age" = ageyrcalc, 
    "Child Under 5" = if_else(ageyrcalc <= 5, "Yes", "No"), 
    "Child Time in Navi Mumbai" = ve_chliveyr, 
    "Child Sex" = recode(sex, !!!sex_recode), 
    "Child Schooling" = recode(school, !!!child_schooling_recode),
    "Child Education" = recode(chedu, !!!child_schooling_level_recode), 
    "Received All Normal Vaccines" = recode(ve_allvacs, !!!yes_no_recode),
    "Received Typhoid Vaccine" = recode(ve_tvac, !!!yes_no_recode),
    "Typhoid Vaccine Campaign" = recode(tcv_vax, !!!yes_no_recode), 
    "Other Typhoid Vaccine" = recode(typhoid_vax, !!!yes_no_recode), 
    "Other Typhoid Vaccine Type" = 
      case_when(
        ve_ncothtyp_a == 1 ~ "TCV",
        ve_ncothtyp_b == 1 ~ "Polysaccharide", 
        ve_ncothtyp_c == 1 ~ "Not Specified", 
        TRUE ~ NA_character_
      ),
    "Fever in last month" = recode(fev1mo, !!!yes_no_recode), 
    "3 Day Fever (30 days)" = recode(fev3day, !!!yes_no_recode),
    "Fever other symptoms (30 days)" =
      case_when(
      symp_a == 1 ~ "none", 
      symp_b == 1 ~ "cold/runny nose",
      symp_c == 1 ~ "headache",
      symp_d == 1 ~ "bodyache",
      symp_e == 1 ~ "sore throat",
      symp_f == 1 ~ "rash",
      symp_e == 1 ~ "cough",
      symp_g == 1 ~ "ear infection",
      symp_h == 1 ~ "skin boils",
      symp_i == 1 ~ "diarrhea",
      symp_j == 1 ~ "abdominal pain",
      TRUE ~ NA_character_
    ), 
    "Fever where child missed school (30 days)" = recode(fever_sch30, !!!yes_no_school_recode ), 
    "Fever where hh member missed work (30 days)" = recode(fever_work30, !!!yes_no_recode), 
    "Fever where perscribed antibiotics (30 days)" = recode(fever_antibiotics30, !!!yes_no_recode), 
    "Fever where child missed school (3 months)" = recode(fever_sch3, !!!yes_no_school_recode), 
    "Child fever where hh member missed work (3 months)" = recode(fever_work3, !!!yes_no_recode),
    "Fever where perscribed antibiotics (3 months)" = recode(fever_antibiotics3, !!!yes_no_recode), 
    "Sought treatment for Fever (30 days)" = recode(trt, !!!yes_no_recode), 
    "Fever Treatment Location (30 days)" = 
      case_when(
        ccs_trtloc_a == "1" | ccs_trtloc_b == "1" | ccs_trtloc_c == "1" |ccs_trtloc_d == "1" ~ "study site", 
        ccs_trtloc_a == "1" | ccs_trtloc_b == "1" | ccs_trtloc_c == "1" |ccs_trtloc_d == "1"| ccs_trtloc_e == "1" | ccs_trtloc_f == "1" | ccs_trtloc_g == "1" | ccs_trtloc_i == "1" ~ "Hospital (including study sites)", 
        ccs_trtloc_j == "1" ~ "Private physician/clinic",
        ccs_trtloc_k == "1" ~ "Pharmacy",
        TRUE ~ NA_character_
      ), 
    "Study Site Treatment Location" = 
      if_else(
      ccs_trtloc_a == "1" |
        ccs_trtloc_b == "1" |
        ccs_trtloc_c == "1" |
        ccs_trtloc_d == "1" , 
      "Yes", "No"), 
    "Fever where child missed school (12 months)" = recode(fever_sch, !!!yes_no_school_recode ), 
    "Fever where hh member missed work (12 months)" = recode(fever_work, !!!yes_no_recode), 
    "Fever where perscribed antibiotics (12 months)" = recode(fever_antibiotics, !!!yes_no_recode), 
    "Fever with hospitalization (12 months)" = recode(hosp, !!! yes_no_recode), 
    "Hospitalization location (12 months)" = if_else(hosp_admit_site == 1, "study site", "not study site")
  )
  
ch_vars <- 
  c(
    "Houshold Size",
    "Chuld age",
    "Child Under 5",
    "Child Time in Navi Mumbai",
    "Child Sex",
    "Child Schooling",
    "Child Education", 
    "Typhoid Vaccine Campaign", 
    "Other Typhoid Vaccine",
    "Fever in last month",
    "3 Day Fever",
    "Fever Treatment",
    "Study Site Treatment Location"
    )

ch_vars_dem <- 
  c(
    "Houshold Size",
    "Chuld age", 
    "Child Under 5",
    "Child Time in Navi Mumbai",
    "Child Sex",
    "Child Schooling",
    "Child Education"
    )

ch_vars_health_vax <- 
  c(
    "Received All Normal Vaccines", 
    "Received Typhoid Vaccine",
    "Typhoid Vaccine Campaign",
    "Other Typhoid Vaccine",
    "Other Typhoid Vaccine Type"
    )

ch_vars_health_fever <- 
  c(
    "Fever in last month",
    "3 Day Fever (30 days)",
    "Fever other symptoms (30 days)",
    "Fever where child missed school (30 days)", 
    "Fever where hh member missed work (30 days)", 
    "Fever where perscribed antibiotics (30 days)", 
    "Sought treatment for Fever (30 days)", 
    "Fever Treatment Location (30 days)", 
    "Fever where child missed school (3 months)", 
    "Child fever where hh member missed work (3 months)", 
    "Fever where perscribed antibiotics (3 months)",
    "Fever where child missed school (12 months)", 
    "Fever where hh member missed work (12 months)", 
    "Fever where perscribed antibiotics (12 months)", 
    "Fever with hospitalization (12 months)", 
    "Hospitalization location (12 months)" 
  )

ch_vars_health_fever2 <- 
  c(
    "Fever in last month",
    "3 Day Fever (30 days)",
    "Sought treatment for Fever (30 days)", 
    "Fever Treatment Location (30 days)", 
    "Fever where child missed school (12 months)", 
    "Fever with hospitalization (12 months)", 
    "Hospitalization location (12 months)" 
  )

ch_cat_vars_dem <- c("Child Schooling", "Child Education")
ch_cat_vars_health_vax <- c("Other Typhoid Vaccine Type")
ch_cat_vars_health_fever <- c("Fever other symptoms (30 days)", "Fever Treatment Location (30 days)" )


```


```{r}

#Splitting up individually into tables 
# ccs_data_hh %>% 
#   filter(status == "INT") %>% 
#   group_by(PHASE) %>% 
#   mutate(
#     hh_edu = recode(ve_hheadedu, !!!hh_edu_recode)
#   ) %>% 
#  count(hh_edu) %>% 
#  pivot_wider(names_from = PHASE, names_prefix = "Phase ", values_from = n) %>% 
#  transmute("Education status" = hh_edu, `Phase 1`, `Phase 2`)
  
hh_vars <- c("Number of Children", "Age Respondent", "Sex Respondent", "Household Head (HH)","HH Education", "HH Occupation", "Spending (Rupees)", "Drinking Water Source", "Water Treatment", "Hand Wash Location", "Hand Wash Water", "Hand Wash Soap", "Toilet Type", "Shared Toilet")

hh_cat_vars <-  c("Household Head (HH)","HH Education", "HH Occupation", "Drinking Water Source", "Hand Wash Location", "Toilet Type")

tab2 <- CreateTableOne(vars = hh_vars, data = ccs_data_hh_formatted, factorVars = hh_cat_vars, strata = "PHASE")

tab2
```
#Child Demographics 
```{r}
tab3 <- CreateTableOne(vars = ch_vars_dem, data = ccs_dara_ch_formatted, factorVars = ch_cat_vars_dem, strata = "PHASE")

tab3
```
#Child healthcare vaccines
```{r}
tab4 <- CreateTableOne(vars = ch_vars_health_vax, data = ccs_dara_ch_formatted, factorVars = ch_cat_vars_health_vax, strata = "PHASE")
tab4

```
#Child healthcare fever
```{r}
tab4 <- CreateTableOne(vars = ch_vars_health_fever, data = ccs_dara_ch_formatted, factorVars = ch_cat_vars_health_fever, strata = "PHASE")

tab4
```

#Basic Frequencies 

```{r}

#number of hh included in the study 
ccs_data_hh %>% 
  filter(status == "INT")
  

# Number of individual childrene included 
ccs_data_ch %>% 
  filter(status == "INT") %>% 
  mutate(
    child_under5 = if_else(liveyr <= 5, 1, 0),
    hosp_studysite = if_else(hosp_admit_a == 1 | hosp_admit_b == 1 | hosp_admit_c == 1 | hosp_admit_d == 1 | hosp_admit_e == 1, 1, 0)
         ) %>% 
  count(hosp_studysite, child_under5, PHASE)


#view(ccs_data_ch)
ccs_data_ch %>% 
  filter(status == "INT") %>% 
  mutate(child_under5 = if_else(liveyr <= 5, 1, 0)) %>% 
  count(child_under5, PHASE, hosp)
```

## Mapping Hospital use
```{r}
ccs_data_ch_cdc %>% 
  filter(!is.na(hosp_admit_site)) %>% 
  ggplot(aes(color = as_factor(hosp_admit_site))) + 
  geom_point(aes(ccs_gps1_latitude, ccs_gps1_longitude)) +
  scale_color_manual(values = c("black", "red"))

ccs_data_ch_cdc %>% 
  filter(!is.na(hosp_admit_site) | trt == 1 ) %>% 
  write_csv()
  
  
```

```{r}
tab5 <- CreateTableOne(vars = ch_vars_health_fever2, data = ccs_dara_ch_formatted, factorVars = ch_cat_vars_health_fever, strata = "Received Typhoid Vaccine")

tab5
```

